### ISSUE TITLE
GeneratedAppGlideModuleImpl is implemented incorrectly

### ISSUE THREAD

**Issue by ahmedosama5200** [chinalwb/Android-Rich-text-Editor#114]
I have the following error:
java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:344)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:336)
        at com.bumptech.glide.Glide.get(Glide.java:179)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:776)

**Comment by chinalwb** [comment]
I'll check and get back to you, thanks!

**Comment by chinalwb** [comment]
@ahmedosama5200 I found starting from glide 4.10.0, it has been migrated to AndroidX. And with this version and 4.11.0, I cannot build successfully, so could you please try with 4.9.0 if possible? Thanks.

**Comment by ahmedosama5200** [comment]
It works with glide 4.9.0, But I think you should migrate it to AndroidX. I really loved your work. Another thing, Can you enable cropping the image using a library like ucrop, and then viewing the image inside a bounded box. Currently the image fills up the width of the screen which is not looking good.

**Comment by ahmedosama5200** [comment]
There is another problem with right to left languages, quotes functionality does not seem to be working with it.

**Comment by chinalwb** [comment]
@ahmedosama5200 really appreciate your suggestions! I'd like to implement the requests when I have time, and I'd love to see some Pull Requests from all of you great guys as well! Because ARE toolbar + toolitem is flexible to be configured and inserted new features!

Again, thank you!!
