### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by halig313** [chinalwb/Android-Rich-text-Editor#143]
hello iam using your library and iam facing this Exception:

{**java.lang.IndexOutOfBoundsException: setSpan (75 ... 52) has end before start**
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1314)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:682)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:674)
        at com.chinalwb.are.styles.ARE_ABS_Dynamic_Style.applyNewStyle(ARE_ABS_Dynamic_Style.java:87)
        at com.chinalwb.are.styles.toolitems.styles.ARE_Style_FontColor.onPickColor(ARE_Style_FontColor.java:145)
        at com.chinalwb.are.colorpicker.ColorPickerView$1.onClick(ColorPickerView.java:108)
        at android.view.View.performClick(View.java:7352)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27800)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)}

the problem happens when i select a part of edittext and then i want to use FontColor on it;
is it any way to check Span start and end before styling it?

**Comment by pavelpoley** [comment]
Same issue
