### ISSUE TITLE
with hilt, throws RuntimeException: Unable to start activity ComponentInfo{}

### ISSUE THREAD

**Issue by fitareq** [chinalwb/Android-Rich-text-Editor#160]
java.lang.RuntimeException: Unable to start activity ComponentInfo{}
Error inflating class com.chinalwb.are.AREditor

**Comment by fitareq** [comment]
Here is the full error log:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.group.dird.dms, PID: 12768
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.group.dird.dms/com.group.dird.dms.ui.file_approval.FileApprovalActivity}: android.view.InflateException: Binary XML file line #12 in com.group.dird.dms:layout/activity_file_approval: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Error inflating class com.chinalwb.are.AREditor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: android.view.InflateException: Binary XML file line #12 in com.group.dird.dms:layout/activity_file_approval: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Error inflating class com.chinalwb.are.AREditor
     Caused by: android.view.InflateException: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Error inflating class com.chinalwb.are.AREditor
     Caused by: android.view.InflateException: Binary XML file line #220 in com.group.dird.dms:layout/fragment_file_approval: Error inflating class com.chinalwb.are.AREditor
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.group.dird.dms.databinding.FragmentFileApprovalBinding.inflate(FragmentFileApprovalBinding.java:144)
        at com.group.dird.dms.ui.file_approval.FileApprovalFragment.onCreateView(FileApprovalFragment.kt:48)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
E/AndroidRuntime:     at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:392)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:281)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:140)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:319)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:298)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.group.dird.dms.databinding.ActivityFileApprovalBinding.inflate(ActivityFileApprovalBinding.java:43)
        at com.group.dird.dms.databinding.ActivityFileApprovalBinding.inflate(ActivityFileApprovalBinding.java:37)
        at com.group.dird.dms.ui.file_approval.FileApprovalActivity.onCreate(FileApprovalActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
        at com.chinalwb.are.styles.toolbar.ARE_Toolbar.<init>(ARE_Toolbar.java:357)
        at com.chinalwb.are.styles.toolbar.ARE_Toolbar.<init>(ARE_Toolbar.java:352)
        at com.chinalwb.are.styles.toolbar.ARE_Toolbar.<init>(ARE_Toolbar.java:348)
        at com.chinalwb.are.AREditor.initGlobal(AREditor.java:156)
        at com.chinalwb.are.AREditor.init(AREditor.java:148)
        at com.chinalwb.are.AREditor.<init>(AREditor.java:135)
        at com.chinalwb.are.AREditor.<init>(AREditor.java:122)
        	... 54 more
