### ISSUE TITLE
ContextThemeWrapper cannot be cast Activity when use own Toolbar

### ISSUE THREAD

**Issue by ebysofyan** [chinalwb/Android-Rich-text-Editor#76]
I wanna use my own toolbar by set my toolbar as ActionBar
```
setSupportActionBar(_toolbar)
supportActionBar?.apply { setDisplayHomeAsUpEnabled(true) }
```

But there is error on Util.java because context cast with `Activity` without check instanceof the object first
```
Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at com.chinalwb.are.Util.getPixelByDp(Util.java:156)
        at com.chinalwb.are.AREditText.init(AREditText.java:108)
        at com.chinalwb.are.AREditText.<init>(AREditText.java:91)
        at com.chinalwb.are.AREditText.<init>(AREditText.java:80)
```

**Comment by chinalwb** [comment]
Wow.. Great
