### ISSUE TITLE
Are_Hr导致崩溃

### ISSUE THREAD

**Issue by vanzh** [chinalwb/Android-Rich-text-Editor#90]
如下操作必现，在添加一个AreHr之后，光标移动到该AreHr行首，再次点击添加Are_Hr ，崩溃。
崩溃日志 ：
2019-08-29 17:50:44.881 9982-9982/com.chinalwb.are.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chinalwb.are.demo, PID: 9982
    java.lang.IndexOutOfBoundsException: 74, -2
        at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
        at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
        at android.text.DynamicLayout.-wrap0(Unknown Source:0)
        at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:750)
        at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:779)
        at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1292)
        at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:647)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
        at com.chinalwb.are.styles.ARE_Hr$1.onClick(ARE_Hr.java:51)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by chinalwb** [comment]
多谢反馈。之前开发时遇到过由于Android8.0上的textview导致的闪退。我看下。

**Comment by chinalwb** [comment]
@vanzh 我在Android 8的模拟器测试 没重现啊

**Comment by vanzh** [comment]
可能是我改动了什么东西导致，你的最新的demo 没有这个问题。
