### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by naveen-nuveda** [chinalwb/Android-Rich-text-Editor#93]
I tried to convert this below code in demo App But giving this error 

> Process: com.chinalwb.are.demo, PID: 6747
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chinalwb.are.demo/com.chinalwb.are.demo.ARE_DefaultToolbarActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:2036)
        at com.chinalwb.are.android.inner.HtmlToSpannedConverter.getFontSize(Html.java:1699)
        at com.chinalwb.are.android.inner.HtmlToSpannedConverter.startCssStyle(Html.java:1281)
        at com.chinalwb.are.android.inner.HtmlToSpannedConverter.handleStartTag(Html.java:916)
        at com.chinalwb.are.android.inner.HtmlToSpannedConverter.startElement(Html.java:1483)
        at org.ccil.cowan.tagsoup.Parser.push(Parser.java:795)
        at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1062)
        at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1017)
        at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:624)
        at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
        at com.chinalwb.are.android.inner.HtmlToSpannedConverter.convert(Html.java:855)
        at com.chinalwb.are.android.inner.Html.fromHtml(Html.java:286)
        at com.chinalwb.are.AREditText.fromHtml(AREditText.java:344)
        at com.chinalwb.are.demo.ARE_DefaultToolbarActivity.setHtml(ARE_DefaultToolbarActivity.java:124)
        at com.chinalwb.are.demo.ARE_DefaultToolbarActivity.initToolbar(ARE_DefaultToolbarActivity.java:104)
        at com.chinalwb.are.demo.ARE_DefaultToolbarActivity.onCreate(ARE_DefaultToolbarActivity.java:56)

**Code in ARE_DefaultToolbarActivity.java**
`String html = "<p>&nbsp;</p><p>1)Overview&nbsp;</p><p>2)Ontology documentation&nbsp;</p><p><span style=\"font-size: 0.875rem;\">3)Ontology visuals</span><br></p><p>4)Ontology driven systems</p><div><br></div>";`

`mEditText.fromHtml(html);`

**Comment by chinalwb** [comment]
I think the problem could be current code doesn't support rem unit. Can you please change it to px and try again? 

Let me know your result. Thanks.

**Comment by naveen-nuveda** [comment]
In my scenario, I can't change rem to px. The HTML text was generated by web side application when we using the same application as the android app. We are getting a dynamic text from our server which contains rem or px anything.

I have given this workaround by analyzing the error I got. 

**Html.java**
```
 private static int getFontSize(String fontSizePx) {
        int pxIndex = fontSizePx.indexOf("px");
        if(pxIndex == -1) // checked for unknown index and returned default size
            return 18;
        String fontSizeStr = fontSizePx.substring(0, pxIndex);
        try {
            return Integer.parseInt(fontSizeStr);
        } catch (NumberFormatException e) {
            return 18;
        }
    }
```

**Comment by chinalwb** [comment]
Ok as you have found the related code, a better way could be parsing the rem number out, then turn it into px accordingly, I believe you know how to do that.
